version: '3.7'

services:
  slim:
    image: php-postgresql
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: arq-web
      POSTGRES_USER: lucasfrias
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  front:
    image: php:7-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t /var/www
    ports:
      - 8081:8080
    volumes:
      - /home/lucasfrias/webWorkspace/arq-web-front:/var/www